# RSI + close_feat cross_over BB middle (pre_shift=0) for sensitivity check (AUDUSD)

features:
  rsi_{{rsi.length}}:
    kind: rsi
    on: close
    params: { length: "{{rsi.length}}" }

  bb_{{bb.window}}_{{bb.mult}}:
    kind: bb
    on: close
    params: { window: "{{bb.window}}", mult: "{{bb.mult}}" }

  close_feat:
    kind: identity
    on: close
    params: {}

plan:
  preconditions:
    - { op: eq, left: "session_active", right: true }
  entries:
    - { op: gt, left: "rsi_{{rsi.length}}", right: "{{entry.rsi_gt}}" }
    - { op: cross_over, left: "close_feat", right: "bb_{{bb.window}}_{{bb.mult}}_middle" }
  exits:
    - { op: lt, left: "rsi_{{rsi.length}}", right: "{{exit.rsi_lt}}" }

space:
  rsi.length:   { type: int,   low: 5,  high: 40, step: 1 }
  bb.window:    { type: int,   low: 10, high: 40, step: 2 }
  bb.mult:      { type: float, low: 1.0, high: 3.0, step: 0.25 }
  entry.rsi_gt: { type: int,   low: 38, high: 65, step: 1 }
  exit.rsi_lt:  { type: int,   low: 25, high: 55, step: 1 }

universe:
  symbols: [AUDUSD]
  timeframes: [m15]

sessions:
  - { name: ALLDAY, type: all, tz: UTC }
  - { name: LONDON, type: window, start: "08:00", end: "17:00", tz: "Europe/London" }

run_params:
  fees: 0.00016
  slippage: 0.0001
  size: 1.0
  size_type: percent
  init_cash: 100000
  leverage: 1.0
  cash_sharing: true
  accumulate: true
  max_entries: 3
  sl_trail: true
  max_positions: 3
  session_preset: { name: ALLDAY, type: all, tz: UTC }
  sl_pct: 0.003
  rr: 2.0
